apiVersion: v1
kind: Service
metadata:
    name: "clusterf-b59b"
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    labels:
      app: "clusterf-b59b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "clusterf-b59b"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clusterf-b59b
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: clusterf-b59b
            port:
              number: 80
        pathType: Exact