apiVersion: v1
kind: Service
metadata:
    name: "eiriktestcluster2-0bbe"
    labels:
        app: "eiriktestcluster2-0bbe"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "eiriktestcluster2-0bbe"