on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: eirikcontainerregistry.azurecr.io
        username: ${{ secrets.acr_eirikcontainerregistry_username }}
        password: ${{ secrets.acr_eirikcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/ContainerApi" -f  "ContainerApi/NewContainerApi/Dockerfile" -t eirikcontainerregistry.azurecr.io/clusterf:${{ github.sha }} --label dockerfile-path=ContainerApi/NewContainerApi/Dockerfile
        docker push eirikcontainerregistry.azurecr.io/clusterf:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clusterf_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: eirikcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_eirikcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_eirikcontainerregistry_password }}
        secret-name: clusterfdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          eirikcontainerregistry.azurecr.io/clusterf:${{ github.sha }}
        imagepullsecrets: |
          clusterfdockerauth
